-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 01:10:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mobile_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mobile_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobile_store` DEFAULT CHARACTER SET utf8 ;
USE `mobile_store` ;

-- -----------------------------------------------------
-- Table `mobile_store`.`castomers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`castomers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organization` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `e_mail` VARCHAR(45) NULL,
  `postcode` INT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`local_deliverys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`local_deliverys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `employment_date` VARCHAR(45) NULL,
  `work_shift` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`product_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`product_codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_of_product` VARCHAR(45) NULL,
  `price` INT NULL,
  `manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`order_baskets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`order_baskets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity_of_goods` INT NULL,
  `product_code_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_baskets_product_codes_idx` (`product_code_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_baskets_product_codes`
    FOREIGN KEY (`product_code_id`)
    REFERENCES `mobile_store`.`product_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`deliverymans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`deliverymans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`train_deliverys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`train_deliverys` (
  `id` INT NOT NULL,
  `name_of_train` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`air_deliverys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`air_deliverys` (
  `id` INT NOT NULL,
  `name_of_airplane` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`ship_deliverys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`ship_deliverys` (
  `id` INT NOT NULL,
  `name_of_airplane` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`international_deliverys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`international_deliverys` (
  `id` INT NOT NULL,
  `deliverymans_id` INT NOT NULL,
  `train_deliverys_id` INT NOT NULL,
  `air_deliverys_id` INT NOT NULL,
  `ship_deliverys_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organizations_deliverymans1_idx` (`deliverymans_id` ASC) VISIBLE,
  INDEX `fk_organizations_train_deliverys1_idx` (`train_deliverys_id` ASC) VISIBLE,
  INDEX `fk_organizations_air_deliverys1_idx` (`air_deliverys_id` ASC) VISIBLE,
  INDEX `fk_organizations_ship_deliverys1_idx` (`ship_deliverys_id` ASC) VISIBLE,
  CONSTRAINT `fk_organizations_deliverymans1`
    FOREIGN KEY (`deliverymans_id`)
    REFERENCES `mobile_store`.`deliverymans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizations_train_deliverys1`
    FOREIGN KEY (`train_deliverys_id`)
    REFERENCES `mobile_store`.`train_deliverys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizations_air_deliverys1`
    FOREIGN KEY (`air_deliverys_id`)
    REFERENCES `mobile_store`.`air_deliverys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizations_ship_deliverys1`
    FOREIGN KEY (`ship_deliverys_id`)
    REFERENCES `mobile_store`.`ship_deliverys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`client_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`client_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` VARCHAR(45) NULL,
  `delivery_date` VARCHAR(45) NULL,
  `form_of_payment` VARCHAR(45) NULL,
  `delivery_id` INT NOT NULL,
  `castomer_id` INT NOT NULL,
  `product_code_id` INT NOT NULL,
  `international_delivery_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_orders_deliverys1_idx` (`delivery_id` ASC) VISIBLE,
  INDEX `fk_client_orders_castomers1_idx` (`castomer_id` ASC) VISIBLE,
  INDEX `fk_client_orders_product_codes1_idx` (`product_code_id` ASC) VISIBLE,
  INDEX `fk_client_orders_international_deliverys1_idx` (`international_delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_orders_deliverys1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `mobile_store`.`local_deliverys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_orders_castomers1`
    FOREIGN KEY (`castomer_id`)
    REFERENCES `mobile_store`.`castomers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_orders_product_codes1`
    FOREIGN KEY (`product_code_id`)
    REFERENCES `mobile_store`.`product_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_orders_international_deliverys1`
    FOREIGN KEY (`international_delivery_id`)
    REFERENCES `mobile_store`.`international_deliverys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`iphones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`iphones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`xiaomi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`xiaomi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`samsungs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`samsungs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iphones_id` INT NOT NULL,
  `xiaomi_id` INT NOT NULL,
  `samsungs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phones_iphones1_idx` (`iphones_id` ASC) VISIBLE,
  INDEX `fk_phones_xiaomi1_idx` (`xiaomi_id` ASC) VISIBLE,
  INDEX `fk_phones_samsungs1_idx` (`samsungs_id` ASC) VISIBLE,
  CONSTRAINT `fk_phones_iphones1`
    FOREIGN KEY (`iphones_id`)
    REFERENCES `mobile_store`.`iphones` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_xiaomi1`
    FOREIGN KEY (`xiaomi_id`)
    REFERENCES `mobile_store`.`xiaomi` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_samsungs1`
    FOREIGN KEY (`samsungs_id`)
    REFERENCES `mobile_store`.`samsungs` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile_store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobile_store`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phones_id` INT NULL,
  `product_codes_id` INT NULL,
  INDEX `fk_phones_has_product_codes_product_codes1_idx` (`product_codes_id` ASC) VISIBLE,
  INDEX `fk_phones_has_product_codes_phones1_idx` (`phones_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_phones_has_product_codes_phones1`
    FOREIGN KEY (`phones_id`)
    REFERENCES `mobile_store`.`phones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_has_product_codes_product_codes1`
    FOREIGN KEY (`product_codes_id`)
    REFERENCES `mobile_store`.`product_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
